/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{vue,js,ts,jsx,tsx}",
    "./components/**/*.{vue,js,ts,jsx,tsx}",
    "./layouts/**/*.vue",
    "./pages/**/*.vue",
    "./plugins/**/*.{js,ts}",
    "./nuxt.config.{js,ts}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#00629d",
        "on-primary-fixed": "#001d33",
        "surface-container-highest": "#e0e3e5",
        "primary-fixed-dim": "#98cbff",
        "inverse-on-surface": "#eff1f3",
        "inverse-primary": "#98cbff",
        "primary-fixed": "#cfe5ff",
        "tertiary-fixed-dim": "#ffb77d",
        "outline-variant": "#bec7d4",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#b9c7df",
        "secondary-fixed": "#d5e3fc",
        "secondary": "#515f74",
        "surface-bright": "#f7f9fb",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "on-surface": "#191c1e",
        "surface-container": "#eceef0",
        "error": "#ba1a1a",
        "surface": "#f7f9fb",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#0d1c2e",
        "on-tertiary-fixed": "#2f1500",
        "surface-container-high": "#e6e8ea",
        "surface-variant": "#e0e3e5",
        "secondary-container": "#d5e3fc",
        "on-primary-fixed-variant": "#004a77",
        "surface-dim": "#d8dadc",
        "surface-container-low": "#f2f4f6",
        "on-error": "#ffffff",
        "on-background": "#191c1e",
        "surface-tint": "#00629d",
        "on-primary-container": "#00375a",
        "inverse-surface": "#2d3133",
        "on-secondary-fixed-variant": "#3a485b",
        "on-tertiary-fixed-variant": "#6e3900",
        "tertiary": "#904d00",
        "tertiary-container": "#eb8104",
        "on-surface-variant": "#3f4852",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#00a3ff",
        "background": "#f7f9fb",
        "on-secondary-container": "#57657a",
        "on-tertiary-container": "#522900",
        "outline": "#6f7883",
        "tertiary-fixed": "#ffdcc3"
      },
      fontFamily: {
        "headline": ["'Plus Jakarta Sans'", "sans-serif"],
        "body": ["Outfit", "sans-serif"],
        "label": ["Outfit", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
    },
  },
  plugins: [],
}
